import express from "express";
import users from "./api/v1/users/index.js";
import auth from "./api/v1/auth/index.js";
import posts from "./api/v1/posts/index.js";
import pictures from "./api/v1/pictures/index.js";
import csrf from "./api/v1/index.js";
const rootRouter = express.Router();
rootRouter.use("/api/v1/users", users);
rootRouter.use("/api/v1/auth", auth);
rootRouter.use("/api/v1/posts", posts);
rootRouter.use("/api/v1/pictures", pictures);
rootRouter.use("/api/v1/csrf-token", csrf);
export default rootRouter;
